// import node module libraries
import { v4 as uuid } from "uuid";

export const CategoryNavigation = [
  {
    id: uuid(),
    title: "Dairy, Bread & Eggs",
    icon: "/images/icons/dairy.svg",
    link: "",
    children: [
      { id: uuid(), title: "Milk", link: "" },
      { id: uuid(), title: "Milk Drinks", link: "" },
      { id: uuid(), title: "Curd & Yogurt", link: "" },
      { id: uuid(), title: "Eggs", link: "" },
      { id: uuid(), title: "Bread", link: "" },
      { id: uuid(), title: "Buns & Bakery", link: "" },
      { id: uuid(), title: "Butter & More", link: "" },
      { id: uuid(), title: "Cheese", link: "" },
      { id: uuid(), title: "Paneer & Tofu", link: "" },
      { id: uuid(), title: "Cream & Whitener", link: "" },
      { id: uuid(), title: "Condensed Milk", link: "" },
      { id: uuid(), title: "Vegan Drinks", link: "" },
    ],
  },
  {
    id: uuid(),
    title: "Snacks & Munchies",
    icon: "/images/icons/snacks.svg",
    link: "",
    children: [
      { id: uuid(), title: "Chips & Crisps", link: "" },
      { id: uuid(), title: "Nachos", link: "" },
      { id: uuid(), title: "Popcorn", link: "" },
      { id: uuid(), title: "Bhujia & Mixtures", link: "" },
      { id: uuid(), title: "Namkeen Snacks", link: "" },
      { id: uuid(), title: "Healthy Snacks", link: "" },
      { id: uuid(), title: "Cakes & Rolls", link: "" },
      { id: uuid(), title: "Energy Bars", link: "" },
      { id: uuid(), title: "Papad & Fryums", link: "" },
      { id: uuid(), title: "Rusks & Wafers", link: "" },
    ],
  },
  {
    id: uuid(),
    title: "Fruits & Vegetables",
    icon: "/images/icons/fruit.svg",
    link: "",
    children: [
      { id: uuid(), title: "Fresh Vegetables", link: "" },
      { id: uuid(), title: "Herbs & Seasonings", link: "" },
      { id: uuid(), title: "Fresh Fruits", link: "" },
      { id: uuid(), title: "Organic Fruits & Vegetables", link: "" },
      { id: uuid(), title: "Cuts & Sprouts", link: "" },
      { id: uuid(), title: "Exotic Fruits & Veggies", link: "" },
      { id: uuid(), title: "Flower Bouquets, Bunches", link: "" },
    ],
  },
  {
    id: uuid(),
    title: "Cold Drinks & Juices",
    icon: "/images/icons/wine.svg",
    link: "",
    children: [
      { id: uuid(), title: "Soft Drinks", link: "" },
      { id: uuid(), title: "Fruit Juices", link: "" },
      { id: uuid(), title: "Coldpress", link: "" },
      { id: uuid(), title: "Energy Drinks", link: "" },
      { id: uuid(), title: "Water & Ice Cubes", link: "" },
      { id: uuid(), title: "Soda & Mixers", link: "" },
      { id: uuid(), title: "Concentrates & Syrups", link: "" },
      { id: uuid(), title: "Detox & Energy Drinks", link: "" },
      { id: uuid(), title: "Juice Collection", link: "" },
    ],
  },
  {
    id: uuid(),
    title: "Breakfast & Instant Food",
    icon: "/images/icons/baby-food.svg",
    link: "",
    children: [
      { id: uuid(), title: "Batter", link: "" },
      { id: uuid(), title: "Breakfast Cereal", link: "" },
      { id: uuid(), title: "Noodles, Pasta & Soup", link: "" },
      { id: uuid(), title: "Frozen Non-Veg Snackss", link: "" },
      { id: uuid(), title: "Frozen Veg", link: "" },
      { id: uuid(), title: "Vermicelli", link: "" },
      { id: uuid(), title: "Instant Mixes", link: "" },
    ],
  },
  {
    id: uuid(),
    title: "Bakery & Biscuits",
    icon: "/images/icons/baby-food.svg",
    link: "",
    children: [
      { id: uuid(), title: "Cookies", link: "" },
      { id: uuid(), title: "Glucose & Marie", link: "" },
      { id: uuid(), title: "Sweet & Salty", link: "" },
      { id: uuid(), title: "Healthy & Digestive", link: "" },
      { id: uuid(), title: "Cream Biscuits", link: "" },
      { id: uuid(), title: "Rusks & Wafers", link: "" },
      { id: uuid(), title: "Cakes & Rolls", link: "" },
      { id: uuid(), title: "Buns & Bakery", link: "" },
    ],
  },
  {
    id: uuid(),
    title: "Chicken, Meat & Fish",
    icon: "/images/icons/baby-food.svg",
    link: "",
    children: [
      { id: uuid(), title: "Chicken", link: "" },
      { id: uuid(), title: "Sausage, Salami & Ham", link: "" },
      { id: uuid(), title: "Exotic Meat", link: "" },
      { id: uuid(), title: "Eggs", link: "" },
      { id: uuid(), title: "Frozen Non-Veg Snacks", link: "" },
    ],
  },
];

export const category2Data = [
  {
    id: uuid(),
    title: "Dairy, Bread & Eggs",
    icon: "/images/icons/dairy.svg",
    link: "",
    children: [
      { id: uuid(), title: "Milk", link: "" },
      { id: uuid(), title: "Milk Drinks", link: "" },
      { id: uuid(), title: "Curd & Yogurt", link: "" },
      { id: uuid(), title: "Eggs", link: "" },
      { id: uuid(), title: "Bread", link: "" },
      { id: uuid(), title: "Buns & Bakery", link: "" },
      { id: uuid(), title: "Butter & More", link: "" },
      { id: uuid(), title: "Cheese", link: "" },
      { id: uuid(), title: "Paneer & Tofu", link: "" },
      { id: uuid(), title: "Cream & Whitener", link: "" },
      { id: uuid(), title: "Condensed Milk", link: "" },
      { id: uuid(), title: "Vegan Drinks", link: "" },
    ],
  },
  {
    id: uuid(),
    title: "Snacks & Munchies",
    icon: "/images/icons/snacks.svg",
    link: "",
    children: [
      { id: uuid(), title: "Chips & Crisps", link: "" },
      { id: uuid(), title: "Nachos", link: "" },
      { id: uuid(), title: "Popcorn", link: "" },
      { id: uuid(), title: "Bhujia & Mixtures", link: "" },
      { id: uuid(), title: "Namkeen Snacks", link: "" },
      { id: uuid(), title: "Healthy Snacks", link: "" },
      { id: uuid(), title: "Cakes & Rolls", link: "" },
      { id: uuid(), title: "Energy Bars", link: "" },
      { id: uuid(), title: "Papad & Fryums", link: "" },
      { id: uuid(), title: "Rusks & Wafers", link: "" },
    ],
  },
  {
    id: uuid(),
    title: "Fruits & Vegetables",
    icon: "/images/icons/fruit.svg",
    link: "",
    children: [
      { id: uuid(), title: "Fresh Vegetables", link: "" },
      { id: uuid(), title: "Herbs & Seasonings", link: "" },
      { id: uuid(), title: "Fresh Fruits", link: "" },
      { id: uuid(), title: "Organic Fruits & Vegetables", link: "" },
      { id: uuid(), title: "Cuts & Sprouts", link: "" },
      { id: uuid(), title: "Exotic Fruits & Veggies", link: "" },
      { id: uuid(), title: "Flower Bouquets, Bunches", link: "" },
    ],
  },
  {
    id: uuid(),
    title: "Cold Drinks & Juices",
    icon: "/images/icons/wine.svg",
    link: "",
    children: [
      { id: uuid(), title: "Soft Drinks", link: "" },
      { id: uuid(), title: "Fruit Juices", link: "" },
      { id: uuid(), title: "Coldpress", link: "" },
      { id: uuid(), title: "Energy Drinks", link: "" },
      { id: uuid(), title: "Water & Ice Cubes", link: "" },
      { id: uuid(), title: "Soda & Mixers", link: "" },
      { id: uuid(), title: "Concentrates & Syrups", link: "" },
      { id: uuid(), title: "Detox & Energy Drinks", link: "" },
      { id: uuid(), title: "Juice Collection", link: "" },
    ],
  },
  {
    id: uuid(),
    title: "Baby Care",
    icon: "/images/icons/baby-food.svg",
    link: "",
    children: [
      { id: uuid(), title: "Diapers, Wipes & More", link: "" },
      { id: uuid(), title: "Baby Food", link: "" },
      { id: uuid(), title: "Bath & Hair Care", link: "" },
      { id: uuid(), title: "Oral & Nasal Care", link: "" },
      { id: uuid(), title: "Baby Skin Care Online", link: "" },
      { id: uuid(), title: "Cleaning Needs Online", link: "" },
      { id: uuid(), title: "Feeding Accessories Online", link: "" },
    ],
  },
  {
    id: uuid(),
    title: "Bakery & Biscuits",
    icon: "/images/icons/bakery.svg",
    link: "",
    children: [
      { id: uuid(), title: "Cookies", link: "" },
      { id: uuid(), title: "Glucose & Marie", link: "" },
      { id: uuid(), title: "Sweet & Salty", link: "" },
      { id: uuid(), title: "Healthy & Digestive", link: "" },
      { id: uuid(), title: "Cream Biscuits", link: "" },
      { id: uuid(), title: "Rusks & Wafers", link: "" },
      { id: uuid(), title: "Cakes & Rolls", link: "" },
      { id: uuid(), title: "Buns & Bakery", link: "" },
    ],
  },
  {
    id: uuid(),
    title: "Chicken, Meat & Fish",
    icon: "/images/icons/fish.svg",
    link: "",
    children: [
      { id: uuid(), title: "Chicken", link: "" },
      { id: uuid(), title: "Sausage, Salami & Ham", link: "" },
      { id: uuid(), title: "Exotic Meat", link: "" },
      { id: uuid(), title: "Eggs", link: "" },
      { id: uuid(), title: "Frozen Non-Veg Snacks", link: "" },
    ],
  },
];
