// import node module libraries
import {
  Apple,
  Arrow90degDown,
  Bag,
  Cart,
  Gear,
  GooglePlay,
  Headphones,
  House,
  Images,
  Infinity,
  ListTask,
  Newspaper,
  People,
  QuestionCircle,
  Shop,
  Star,
} from "react-bootstrap-icons";
import { v4 as uuid } from "uuid";

export const DashboardMenu = [
  {
    id: uuid(),
    title: "Dashboard",
    icon: <House />,
    link: "/dashboard",
    isActive: true,
  },
  {
    id: uuid(),
    title: "Store Managements",
    icon: "",
    grouptitle: true,
  },
  {
    id: uuid(),
    title: "Products",
    icon: <Cart />,
    link: "/dashboard/products",
    isActive: true,
  },
  {
    id: uuid(),
    title: "Categories",
    icon: <ListTask />,
    link: "/dashboard/categories",
    isActive: true,
  },
  {
    id: uuid(),
    title: "Orders",
    icon: <Bag />,
    link: "#",
    isActive: true,
    children: [
      {
        id: uuid(),
        title: "List",
        link: "/dashboard/order-list",
        isActive: true,
      },
      { id: uuid(), title: "Single", link: "/dashboard/order-single" },
    ],
  },
  {
    id: uuid(),
    title: "Sellers / Vendors",
    icon: <Shop />,
    link: "/dashboard/sellers",
    isActive: true,
  },
  {
    id: uuid(),
    title: "Customers",
    icon: <People />,
    link: "#",
    badge: "New",
    isActive: true,
    children: [
      {
        id: uuid(),
        title: "Customers",
        link: "/dashboard/customers",
        isActive: true,
      },
      {
        id: uuid(),
        title: "Create Customer",
        link: "/dashboard/customers/create-customer",
        isActive: true,
      },
      {
        id: uuid(),
        title: "Edit Customer",
        link: "/dashboard/customers/edit-customer",
      },
    ],
  },
  {
    id: uuid(),
    title: "Reviews",
    icon: <Star />,
    link: "/dashboard/reviews",
    isActive: true,
  },
  {
    id: uuid(),
    title: "Menu Level",
    icon: <Arrow90degDown />,
    link: "#",
    isActive: true,
    children: [
      {
        id: uuid(),
        title: "Two Level",
        link: "#",
        isActive: true,
        children: [
          { id: uuid(), title: "NavItem 1", link: "#", isActive: true },
          { id: uuid(), title: "NavItem 2", link: "#", isActive: true },
        ],
      },
      {
        id: uuid(),
        title: "Three Level",
        link: "#",
        isActive: true,
        children: [
          {
            id: uuid(),
            title: "NavItem 1",
            link: "#",
            isActive: true,
            children: [
              {
                id: uuid(),
                title: "NavChild Item 1",
                link: "#",
                isActive: true,
              },
            ],
          },
          { id: uuid(), title: "NavItem 2", link: "#", isActive: true },
        ],
      },
    ],
  },
  {
    id: uuid(),
    title: "Site Settings",
    badge: "Coming Soon",
    grouptitle: true,
  },
  {
    id: uuid(),
    title: "Blog",
    icon: <Newspaper />,
    badge: "New",
    link: "#",
    isActive: true,
    children: [
      {
        id: uuid(),
        title: "Grid",
        link: "/dashboard/blog/grid",
        isActive: true,
      },
      { id: uuid(), title: "List", link: "/dashboard/blog/list" },
      { id: uuid(), title: "Add Post", link: "/dashboard/blog/new-post" },
    ],
  },
  {
    id: uuid(),
    title: "Media",
    icon: <Images />,
    link: "#",
    isActive: false,
  },
  {
    id: uuid(),
    title: "Store Settings",
    icon: <Gear />,
    link: "#",
    isActive: false,
  },
  {
    id: uuid(),
    title: "Support",
    icon: "",
    badge: "Coming Soon",
    grouptitle: true,
  },
  {
    id: uuid(),
    title: "Support Ticket",
    icon: <Headphones />,
    link: "#",
    isActive: false,
  },
  {
    id: uuid(),
    title: "Help Center",
    icon: <QuestionCircle />,
    link: "#",
    isActive: false,
  },
  {
    id: uuid(),
    title: "How FreshCart Works",
    icon: <i className="bi bi-infinity"></i>,
    link: "#",
    isActive: false,
  },
  {
    id: uuid(),
    title: "Our Apps",
    icon: "",
    badge: "",
    grouptitle: true,
  },
  {
    id: uuid(),
    title: "Apple Store",
    icon: <Apple />,
    link: "#",
    isActive: false,
  },
  {
    id: uuid(),
    title: "Google Play Store",
    icon: <GooglePlay />,
    link: "#",
    isActive: false,
  },
];
