// import node module libraries
import { v4 as uuid } from "uuid";

export const docsNavigation = [
  {
    id: uuid(),
    title: "Getting Started",
    children: [
      { id: uuid(), name: "Introduction", link: "/docs" },
      {
        id: uuid(),
        name: "Environment setup",
        link: "/docs/environment-setup",
      },
      { id: uuid(), name: "Getting Started", link: "/docs/getting-started" },
      { id: uuid(), name: "Customize Theme", link: "/docs/customize-theme" },
      { id: uuid(), name: "API Integraion", link: "/docs/api-integration" },
      { id: uuid(), name: "File Structure", link: "/docs/file-structure" },
      {
        id: uuid(),
        name: "Resources & assets",
        link: "/docs/resources-assets",
      },
      { id: uuid(), name: "Changelog", link: "/docs/changelog" },
    ],
  },
  {
    id: uuid(),
    title: "Foundation",
    children: [
      { id: uuid(), name: "Typography", link: "/docs/foundation/typography" },
      { id: uuid(), name: "Colors", link: "/docs/foundation/colors" },
      { id: uuid(), name: "Shadows", link: "/docs/foundation/shadows" },
    ],
  },
  {
    id: uuid(),
    title: "Components (Freshcart)",
    children: [
      { id: uuid(), name: "Card", link: "/docs/components/card" },
      { id: uuid(), name: "Counter", link: "/docs/components/counter" },
      { id: uuid(), name: "CTA", link: "/docs/components/cta" },
      { id: uuid(), name: "Ecommerce", link: "/docs/components/ecommerce" },
      { id: uuid(), name: "Features", link: "/docs/components/features" },
      { id: uuid(), name: "Filter", link: "/docs/components/filter" },
      { id: uuid(), name: "Footer", link: "/docs/components/footer" },
      { id: uuid(), name: "Form", link: "/docs/components/form" },
      { id: uuid(), name: "List", link: "/docs/components/list" },
      { id: uuid(), name: "Navbar", link: "/docs/components/navbar" },
      {
        id: uuid(),
        name: "Testimonials",
        link: "/docs/components/testimonials",
      },
      { id: uuid(), name: "Review", link: "/docs/components/review" },
      { id: uuid(), name: "Sidebar", link: "/docs/components/sidebar" },
      { id: uuid(), name: "Slider", link: "/docs/components/slider" },
      { id: uuid(), name: "Table", link: "/docs/components/table" },
    ],
  },
  {
    id: uuid(),
    title: "Components",
    children: [
      { id: uuid(), name: "Accordions", link: "/docs/accordions" },
      { id: uuid(), name: "Alerts", link: "/docs/alerts" },
      { id: uuid(), name: "Badge", link: "/docs/badge" },
      { id: uuid(), name: "Breadcrumb", link: "/docs/breadcrumb" },
      { id: uuid(), name: "Buttons", link: "/docs/buttons" },
      { id: uuid(), name: "Button group", link: "/docs/button-group" },
      { id: uuid(), name: "Card", link: "/docs/card" },
      { id: uuid(), name: "Carousel", link: "/docs/carousel" },
      { id: uuid(), name: "Close Button", link: "/docs/close-button" },
      { id: uuid(), name: "Collapse", link: "/docs/collapse" },
      { id: uuid(), name: "Dropdowns", link: "/docs/dropdowns" },
      { id: uuid(), name: "List group", link: "/docs/listgroup" },
      { id: uuid(), name: "Modal", link: "/docs/modal" },
      { id: uuid(), name: "Navs and tabs", link: "/docs/navs-tabs" },
      { id: uuid(), name: "Navbar", link: "/docs/navbar" },
      { id: uuid(), name: "Offcanvas", link: "/docs/offcanvas" },
      { id: uuid(), name: "Pagination", link: "/docs/pagination" },
      { id: uuid(), name: "Placeholders", link: "/docs/placeholders" },
      { id: uuid(), name: "Popovers", link: "/docs/popovers" },
      { id: uuid(), name: "Progress", link: "/docs/progress" },
      { id: uuid(), name: "Scrollspy", link: "/docs/scrollspy" },
      { id: uuid(), name: "Spinners", link: "/docs/spinners" },
      { id: uuid(), name: "Tables", link: "/docs/tables" },
      { id: uuid(), name: "Toasts", link: "/docs/toasts" },
      { id: uuid(), name: "Tooltips", link: "/docs/tooltips" },
    ],
  },
  {
    id: uuid(),
    title: "Forms",
    children: [
      { id: uuid(), name: "Basic Forms", link: "/docs/forms/basic-forms" },
      { id: uuid(), name: "Input Group", link: "/docs/forms/input-group" },
    ],
  },
  {
    id: uuid(),
    title: "Utilities",
    children: [
      { id: uuid(), name: "Background", link: "/docs/utilities/background" },
      { id: uuid(), name: "Borders", link: "/docs/utilities/borders" },
      {
        id: uuid(),
        name: "Colored Links",
        link: "/docs/utilities/colored-links",
      },
      { id: uuid(), name: "Opacity", link: "/docs/utilities/opacity" },
      { id: uuid(), name: "Ratio", link: "/docs/utilities/ratio" },
      { id: uuid(), name: "Stacks", link: "/docs/utilities/stacks" },
      { id: uuid(), name: "Colors", link: "/docs/utilities/text-color" },
      { id: uuid(), name: "Text", link: "/docs/utilities/text" },
      {
        id: uuid(),
        name: "Text truncation",
        link: "/docs/utilities/text-truncation",
      },
      {
        id: uuid(),
        name: "Vertical rule",
        link: "/docs/utilities/vertical-rule",
      },
    ],
  },
];
